runtime: php55
api_version: 1
service: default
#instance_class: B8
#basic_scaling:
 # max_instances: 11
  #idle_timeout: 10m


handlers:
- url: /(.+\.php)$
  script: \1
#  http_headers:
 #   Access-Control-Allow-Origin: http://cricket-exchange-web.appspot.com
#- url:  /_ah/start
 # script: \1

 


